import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";
import type { Harness } from "@/types";

const EXPORT_TEMPLATES: Record<Harness, { path: string; wrapper: (content: string, title: string) => string }> = {
  claude_code: {
    path: ".claude/skills/<name>/SKILL.md",
    wrapper: (content) => content,
  },
  copilot: {
    path: ".github/skills/<name>/SKILL.md",
    wrapper: (content) => content,
  },
  copilot_agent: {
    path: "<name>.agent.md",
    wrapper: (content, title) =>
      `---\nname: ${title}\ndescription: Auto-generated by Skill008\n---\n\n${content}`,
  },
  cursor: {
    path: ".cursor/skills/<name>/SKILL.md",
    wrapper: (content) => content,
  },
  agents_md: {
    path: "AGENTS.md",
    wrapper: (content, title) =>
      `## ${title}\n\n${content}`,
  },
};

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const { searchParams } = new URL(request.url);
  const harness = searchParams.get("harness") as Harness | null;

  const supabase = await createClient();

  const { data: skill } = await supabase
    .from("skills")
    .select("*")
    .eq("id", id)
    .single();

  if (!skill) {
    return NextResponse.json({ error: "Skill not found" }, { status: 404 });
  }

  if (harness && EXPORT_TEMPLATES[harness]) {
    const template = EXPORT_TEMPLATES[harness];
    const slug = skill.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    const path = template.path.replace("<name>", slug);
    const content = template.wrapper(skill.base_content, skill.title);

    return NextResponse.json({
      harness,
      path,
      content,
      filename: path.split("/").pop(),
    });
  }

  // Return all export options
  const slug = skill.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const exports = Object.entries(EXPORT_TEMPLATES).map(([key, template]) => ({
    harness: key,
    path: template.path.replace("<name>", slug),
    content: template.wrapper(skill.base_content, skill.title),
  }));

  return NextResponse.json({ exports });
}
